export struct CellData {
    x: int,
    y: int,
    is_mine: bool,
    is_revealed: bool,
    number: string,
    is_flagged: bool,
}

export component MainWindow inherits Window {
    preferred-width: 573px;
    preferred-height: 653px;
    title: "Minesweeper";

    callback cell_clicked(x: int, y: int);
    callback cell_right_clicked(x: int, y: int);
    in-out property <string> game_status;
    in-out property <int> mines_left;
    in-out property <[CellData]> cells;
    in-out property <int> current_index: 10;
    //in-out property <bool> game_lost: false;

    VerticalLayout {
        alignment: start;
        spacing: 10px;
        padding: 10px;
        timer := Timer {
            interval: 1000ms;
            running: true;
            triggered => {
                current_index -= 1;
                if current_index == 0 {
                    debug("Timer Stop");
                    timer.stop();
                }
            }
        }

        Text {
            text: "Minen: " + root.mines_left;
            font-size: 20px;
            horizontal-alignment: center;
        }

        Text {
            text: root.game_status;
            font-size: 20px;
            horizontal-alignment: center;
        }

        GridLayout {
            spacing: 2px;
            for cell_data in cells: Rectangle {
                width: 35px;
                height: 35px;
                row: cell_data.y;
                col: cell_data.x;
                background: {
                    if cell_data.is_flagged {
                        #44ff44
                    } else if !cell_data.is_revealed {
                        #4444ffff
                    } else if cell_data.is_mine {
                        #ff4444ff
                    } else {
                        #cccccccc
                    }
                }
                border-width: 1px;
                border-color: #000000;
                Text {
                    text: cell_data.number;
                    color: black;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    visible: cell_data.is_revealed && !cell_data.is_flagged;
                }

                Image {
                    source: @image-url("flag.png");
                    width: 30px;
                    height: 30px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    visible: cell_data.is_flagged;
                }

                Image {
                    source: @image-url("bomb.png");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 1 || current_index == 2;
                }

                /* Image {
                    source: @image-url("bomb_1.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 2;
                }*/

                /* Image {
                    source: @image-url("Bomb_2.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 3;
                }*/

                /*Image {
                    source: @image-url("Bomb_3.jpeg");
                    width: 30px;
                    height: 30px;
                }*/

                /*Image {
                    source: @image-url("Bomb_4.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 5;
                }*/

                /*Image {
                    source: @image-url("Bomb_5.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 6;
                }*/

                /*Image {
                    source: @image-url("Bomb_6.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 7;
                }*/

                /*Image {
                    source: @image-url("Bomb_7.jpeg");
                    width: 30px;
                    height: 30px;
                    visible: current_index == 8;
                }*/

                TouchArea {
                    clicked => {
                        cell_clicked(cell_data.x, cell_data.y);
                    }
                    pointer-event(event) => {
                        if (event.button == PointerEventButton.right && event.kind == PointerEventKind.down) {
                            cell_right_clicked(cell_data.x, cell_data.y);
                        }
                    }
                }
            }
        }
    }
}
